### ISSUE TITLE
Build in Ubuntu 14.04

### ISSUE THREAD

**Issue by drpjm** [sampsyo/llvm-pass-skeleton#1]
I'm trying out your skeleton project and I get the following error when building in Ubuntu with LLVM 3.4 and Cmake 2.8.12.2:
```
CMake Error at skeleton/CMakeLists.txt:7 (target_compile_features):
  Unknown CMake command "target_compile_features"
```
Is there some other package needed by CMake?

**Comment by sampsyo** [comment]
Thanks for pointing that out. Looks like that command was added in CMake 3.1: http://www.cmake.org/cmake/help/v3.1/release/3.1.0.html

I'll add a version requirement thing to the script.

**Comment by drpjm** [comment]
Thanks for the update! I will upgrade cmake accordingly.
