### ISSUE TITLE
find_package error in CMakeLists.txt

### ISSUE THREAD

**Issue by mudongliang** [sampsyo/llvm-pass-skeleton#2]
I have the following packages:

    ii  cmake     3.2.2-2      amd64        cross-platform, open-source make system
    ii  llvm      1:3.5-26     amd64        Low-Level Virtual Machine (LLVM)
    ii  llvm-3.5  1:3.5.2-1    amd64        Modular compiler and toolchain technologies
Error happens when executing `cmake ..` in the build directory : 
```
CMake Error at /usr/share/llvm-3.5/cmake/LLVMConfig.cmake:50 (include):
  include could not find load file:

    /usr/lib/llvm-3.5/share/llvm/cmake/LLVMExports.cmake
Call Stack (most recent call first):
  CMakeLists.txt:3 (find_package)


CMake Error at /usr/share/llvm-3.5/cmake/LLVMConfig.cmake:53 (include):
  include could not find load file:

    /usr/lib/llvm-3.5/share/llvm/cmake/LLVM-Config.cmake
Call Stack (most recent call first):
  CMakeLists.txt:3 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/mdl/Repos/Github/llvm-pass-skeleton/CMakeFiles/CMakeOutput.log".
```
What should I do ?

**Comment by sampsyo** [comment]
That's odd. CMake seems to think there are files missing from the LLVM installation. You might try installing it yourself from source.

**Comment by mudongliang** [comment]
![screenshot from 2015-08-24 18-36-13](https://cloud.githubusercontent.com/assets/6214861/9438256/0ed688ae-4a8f-11e5-9066-6c3a529f36cf.png)

I have checked the environment : LLVM_CMAKE_DIR. There are no directories about cmake. Files about cmake are in /usr/share/llvm-3.5/cmake/. 
So I change the environment and errors before do not exist. Maybe this is a bug in Debian llvm package.

**Comment by sampsyo** [comment]
Yeah, occasionally you just need to tell CMake where to look. Glad that worked. And yes, it might be a bug in the Debian packaging.
