### ISSUE TITLE
Getting error : undefined symbol: _ZN4llvm23EnableABIBreakingChecksE

### ISSUE THREAD

**Issue by NidhinMohanCheriyan** [sampsyo/llvm-pass-skeleton#27]
Hi,
I'm getting this error 

$ opt -load /home/nidhin/LLVM/build/build/lib/LLVMMyHello.so -myhe input.ll
Error opening '/home/nidhin/LLVM/build/build/lib/LLVMMyHello.so': /home/nidhin/LLVM/build/build/lib/LLVMMyHello.so: undefined symbol: _ZN4llvm23EnableABIBreakingChecksE
  -load request ignored.
opt: Unknown command line argument '-myhe'.  Try: 'opt --help'
opt: Did you mean '--adce'?

LLVM version is 10
I'm using clang-11

**Comment by sampsyo** [comment]
As the README says, this code is currently for LLVM 3.8. You might be interested in the `containers` branch, which is more up to date (works with LLVM 10.0, as described in #24).
