### ISSUE TITLE
error: clang frontend command failed due to signal (use -v to see invocation)

### ISSUE THREAD

**Issue by SimonXiaoxiao** [sampsyo/llvm-pass-skeleton#32]
I success to run some basic pass methods according to this repo, but in some situations, it seems not to work.

such as when I use some method in Basic Block,

    for(BasicBlock::iterator i = B.begin(); i!= B.end(); i++){
      if(i->getOpcode() == Instruction::Load){
      LoadInst *ld = dyn_cast<LoadInst>(i);
      GetElementPtrInst* gep = dyn_cast<GetElementPtrInst>(ld->getPointerOperand());
      gep->getSourceElementType();
      errs()<<"end here\n";
      } 
    }

Every thing works well until "gep->getSourceElementType();" then it output 

Stack dump:
0.Program arguments: clang -Xclang -load -Xclang ../build/DSPass/libDSPass.so -c test.c 
1.<eof> parser at end of file
2.Per-function optimization
3.Running pass 'Unnamed pass: implement Pass::getPassName()' on function '@main'
 #0 0x00007f3e76c1306a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/local/bin/../lib/libLLVMSupport.so.10+0x17806a)
...
clang-10: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 10.0.0 
Target: x86_64-unknown-linux-gnu
Thread model: posix
...

and when I use #7 , it corrupt early in "ld->getPointerOperand()"

The LLVM and Clang version is 10

**Comment by sampsyo** [comment]
If you're using stuff like `dyn_cast`, you will want to check whether the return value is null. Or just use `cast` instead to check for type mismatches:
https://llvm.org/docs/ProgrammersManual.html#the-isa-cast-and-dyn-cast-templates

In general, this repository is not the right place to ask general questions about how to use LLVM. The LLVM Discourse community might be!
