### ISSUE TITLE
Unable to run the pass

### ISSUE THREAD

**Issue by dorafmon** [sampsyo/llvm-pass-skeleton#4]
Hi when I try to run the pass I got this error, do you know why? I am working on a Mac with a hombbrew installed LLVM.

```
error: unable to load plugin 'build/skeleton/libSkeletonPass.so': 'dlopen(build/skeleton/libSkeletonPass.so, 9): Symbol not found:
      __ZN4llvm12FunctionPass17assignPassManagerERNS_7PMStackENS_15PassManagerTypeE
  Referenced from: build/skeleton/libSkeletonPass.so
  Expected in: flat namespace
 in build/skeleton/libSkeletonPass.so'
```

**Comment by sampsyo** [comment]
Hmm, not I'm not 100% sure. FWIW, you can see what that symbol actually is using `c++filt`:

```
$ c++filt "__ZN4llvm12FunctionPass17assignPassManagerERNS_7PMStackENS_15PassManagerTypeE"
llvm::FunctionPass::assignPassManager(llvm::PMStack&, llvm::PassManagerType)
```

but that doesn't help much here.

So I can reproduce, can you give some full bug-report details? Which version installed from Homebrew, how exactly did you compile, which command did you run, etc.

**Comment by dorafmon** [comment]
Hi, sorry for the delay, will provide the info later.

**Comment by dorafmon** [comment]
Hi, I compiled the pass with ``LLVM_DIR=/usr/local/opt/llvm/share/llvm/cmake cmake ..`` in the ``build`` folder and my llvm version is 3.6.2. Can u reproduce it on your local machine? Thanks!

**Comment by sampsyo** [comment]
Aha! I get that error when I try to use my built-in system clang:

```sh
$ clang -Xclang -load -Xclang build/skeleton/libSkeletonPass.so a.c
error: unable to load plugin 'build/skeleton/libSkeletonPass.so':
      'dlopen(build/skeleton/libSkeletonPass.so, 9): Symbol not found:
      __ZN4llvm12FunctionPass17assignPassManagerERNS_7PMStackENS_15PassManagerTypeE
  Referenced from: build/skeleton/libSkeletonPass.so
  Expected in: flat namespace
 in build/skeleton/libSkeletonPass.so'
```

You'll instead need to use the clang from the LLVM version you built the module against:

```sh
$ /usr/local/opt/llvm/bin/clang -Xclang -load -Xclang build/skeleton/libSkeletonPass.so a.c
```

**Comment by ezgickr** [comment]
what must be in "a.c" file? when I write the terminal comment I get this error:
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
Do you know why?

**Comment by sampsyo** [comment]
That probably means your source file doesn't have a main function (just like any C program).

**Comment by ezgickr** [comment]
Do you mean "a.c" file by the source file ? If you do, I don't have any idea about what the source file must have. I am really new in this subjects, sorry for my silly questions. And thank you for your help.

**Comment by sampsyo** [comment]
Yes. That's the source file that you want to pass through your LLVM analysis.

**Comment by hejian1639** [comment]
```
jiandembp:llvm-pass-skeleton jianhe$ clang -Xclang -load -Xclang ./skeleton/libSkeletonPass.* test.c 
error: unable to load plugin './skeleton/libSkeletonPass.so': 'dlopen(./skeleton/libSkeletonPass.so, 9): Symbol not found: __ZN4llvm23EnableABIBreakingChecksE
  Referenced from: ./skeleton/libSkeletonPass.so
  Expected in: flat namespace
 in ./skeleton/libSkeletonPass.so'
```

I got a similar issue, so is it anything to do with clang and llvm version?
I'm using Mac OS

```
jiandembp:llvm-pass-skeleton jianhe$ clang -v
Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

llvm is compiled for latest code 
` https://github.com/llvm-mirror/llvm.git `

**Comment by sampsyo** [comment]
Yes, as I wrote above, you’re probably invoking the wrong clang.

**Comment by KaushalNaresh** [comment]
Hi,

When I ran my code using
/opt/homebrew/opt/llvm/bin/clang -Xclang -load -Xclang build/skeleton/libSkeletonPass.so a.c

It is not printing "I saw a function called main!"

but it is generating a.out file
